
export enum BlockUrlConstant {
    TextSpan = '/textspan',
    Text = '/text',
    Row = '/row',
    Col = '/col',
    View = '/view',
    Divider = '/divider',
    List = '/list',
    Head = '/head',
    Frame = '/frame',
    Mind = '/flow/mind',
    Group = '/group',
    Board = '/board',
    Outline = '/outline',
    Title = '/title',
    Quote = '/quote',
    Callout = '/callout',
    Code = '/code',
    Katex = '/katex',
    KatexLine = '/katex/line',
    DataGridGallery = '/data-grid/gallery',
    DataGridTable = '/data-grid/table',
    DataGridList = '/data-grid/list',
    DataGridCalendar = '/data-grid/calendar',
    TableStoreBoard = '/data-grid/board'
}