export enum SyncMessageUrl {
    userTalkNotify = '/user/chat/notify',
    userTalkPatchNotify = '/user/chat/patch/notify',
    userPayNotify = '/user/pay/notify',
    userOnlineNotify = '/user/online/notify',
    userOffLineNotify = '/user/offline/notify',
    userPatchStatusNotify = '/user/patch/status/notify',
    userPatchNotify = '/user/patch/notify',
    userJoinOrExitWsNotify = '/user/joinOrExit/ws/notify',
    userFriendChangesNotify = '/user/friend/change/notify',
    userFriendRequestNotify = '/user/friend/request/notify',
    pageItemOperate = '/ws/page/item/operate/notify',
    viewOperate = '/ws/view/operate/notify',
    viewOperates = '/ws/view/operates/notify',
    dateGridOperator = '/ws/datagrid/schema/operate/notify',
    workspaceSync = '/ws/sync',
    channelNotify = '/ws/channel/notify',
    channelDeletedNotify = '/ws/channel/deleted/notify',
    channelPatchNotify = '/ws/channel/patch/notify',
    channelEmojiNotify = '/ws/channel/emoji/notify',
    patchWsNotify = '/ws/patch/notify'
}